server:
  port: 8090
spring:
  data:
    mongodb:
      username: ibrahim
      password: ibrahim
      host: localhost
      port: 27017
      database: ecommerce
      authentication-database: admin